// ข้อมูลคำถาม และคำตอบ
const QuestionDetail  = [
    {
        id: 963,
        name: "Anonymous1",
        date: "11/1/2567",
        time: "11:30 PM",
        detail: "ให้คะแนนยากไหม...",
        edit: false,
        like: ["Anonymous1", "Anonymous6"],
        dislike: ["Anonymous5",],
        answer: [
            {
                id: 1793,
                name: "Anonymous6",
                detail: "ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ",
                edit: false,
                date: "13/1/2567",
                time: "08:30 PM",
            },
            {
                id: 1593,
                name: "Anonymous1",
                detail: "ยากมากกกก ยากสุดดดดๆ ยากมากกกก ยากสุดดดดๆ ยากมากกกก ยากสุดดดดๆ ยากมากกกก ยากสุดดดดๆ ยากมากกกก ยากสุดดดดๆ ยากมากกกก ยากสุดดดดๆ",
                edit: false,
                date: "03/1/2567",
                time: "11:45 PM",
            },
        ],
    },
    {
        id: 759,
        name: "Anonymous3",
        date: "14/1/2567",
        time: "3:30 PM",
        detail: "อาจารย์กดเกรดไหม",
        edit: false,
        like: ["Anonymous6", "Anonymous8"],
        dislike: ["Anonymous5", "Anonymous11", "Anonymous12"],
        answer: [
            {
                id: 5978,
                name: "Anonymous1",
                detail: "กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน กดดัน",
                edit: false,
                date: "11/1/2567",
                time: "11:30 PM",
            },
        ],
    },
    {
        id: 734,
        name: "Anonymous1",
        date: "11/1/2567",
        time: "11:30 PM",
        detail: "Going to you like Vroom vroom vroom Vroom vroom vroom ฉันจะเหยียบให้มิดไมล์ Going to you like Vroom vroom vroom Vroom vroom vroom ให้เธอรักฉันหมดใจ Coming to you like",
        edit: false,
        like: ["Anonymous1", "Anonymous6"],
        dislike: ["Anonymous5",],
        answer: [
            {
                id: 1513,
                name: "Anonymous7",
                detail: "ohhhhhhhhhhhh",
                edit: false,
                date: "11/1/2567",
                time: "11:30 PM",
            },
            {
                id: 5973,
                name: "Anonymous1",
                detail: "hiiiiiiiiiii",
                edit: false,
                date: "11/1/2567",
                time: "11:30 PM",
            },
        ],
    },
    {
        id: 516,
        name: "Anonymous3",
        date: "14/1/2567",
        time: "03:30 PM",
        detail: "ถ้าไม่มีฉัน อยากจะรู้จริง ๆ ว่าเธอจะอยู่ได้หรือเปล่า ก่อนเคยผ่านเรื่องราว ที่มีความสุขและทุกข์ใจ",
        edit: false,
        like: ["Anonymous19", "Anonymous6", "Anonymous8"],
        dislike: ["Anonymous5", "Anonymous11", "Anonymous12"],
        answer: [
            {
                id: 3547,
                name: "Anonymous12",
                detail: "ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ",
                edit: false,
                date: "11/1/2567",
                time: "11:30 PM",
            },
            {
                id: 4936,
                name: "Anonymous1",
                detail: "ยากมากกกก ยากสุดดดดๆ",
                edit: false,
                date: "11/1/2567",
                time: "11:30 PM",
            },
            {
                id: 7896,
                name: "Anonymous36",
                detail: "ไม่รู้ ไม่รู้ ไม่รู้ ไม่เข้าใจ",
                edit: false,
                date: "11/1/2567",
                time: "11:30 PM",
            },
            {
                id: 3654,
                name: "Anonymous1",
                detail: "ยากมากกกก ยากสุดดดดๆ",
                edit: false,
                date: "11/1/2567",
                time: "11:30 PM",
            },
        ],
    },
]

export default QuestionDetail;